// List of solvers to compile:
#include "Chi3.cpp"
#include "Chi2PDC.cpp"
#include "Chi2SFG.cpp"
#include "Chi2AFC.cpp"
#include "Chi2SFGPDC.cpp"
#include "Chi2SFGII.cpp"
#include "Chi2PDCII.cpp"
#include "Chi2SFGOPA.cpp"
#include "Chi2SFGXPM.cpp"

#include "Chi2SHG.cpp"
#include "Chi3THG.cpp"
#include "Chi2SHGOPA.cpp"
#include "Chi2DSFG.cpp"
#include "Chi2SHGXPM.cpp"
#include "Chi2ASHG.cpp"
#include "Chi3GNLSE.cpp"